"""add jira_id to tasks

Revision ID: 46ac12d711e5
Revises: 7882de39216b
Create Date: 2023-08-18 23:53:16.816166

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46ac12d711e5"
down_revision: Union[str, None] = "7882de39216b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("jira_id", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "jira_id")
    # ### end Alembic commands ###
